### ISSUE TITLE
Add roles folder to gitignore.

### ISSUE THREAD

**Issue by mindthecap** [marcosepp/ansible-project-create#2]
Roles folder should be empty by default. To use roles while developing, playbook dependencies are pulled to "roles" folder that is version controlled by default. Default behavior should be to ignore those files and update roles folder only when overridden.

https://github.com/marcosepp/ansible-project-create/blob/131039f1309f85f09b4b2578086206c177a540fa/create-ansible-project#L66

Add roles folder to gitignore:
  echo "#  Add gitignore rules
  #  Ignore virtual environment
  $1-venv
  roles/*
  !roles/README.md" > "$OUT_DIR/$1/.gitignore"

**Comment by marcosepp** [comment]
I think by default roles folder content shouldn't be ignored. Developer might want to develop roles directly to the Ansible project and if it's ignored, it might create other issues. I will add `"!**/README.md" > "$OUT_DIR/$1/.gitignore"` so README.md files will not be ignored.

**Comment by marcosepp** [comment]
To follow Ansible best practices I will add `roles/*` to `.gitignore`. Developers should use ansible-requirements.yml to install roles during project execution.
